image:
  file: .gitpod.Dockerfile
checkoutLocation: '.'
tasks:
  - name: Clean root and grab useful exercises.
    before: |
      rm -rf content
      rm -rf .git
      rm .gitpod*
      rm .docker*
      rm -rf .github   #remove laters, for CICD testing
      sudo mv /home/gitpod/cicd-exercises/* .
      git init
      git add .
      git commit -m "Initial commit"
      exit 0
